### ISSUE TITLE
Pip install groundingdino-py error

### ISSUE THREAD

**Issue by skylning** [opengeos/segment-geospatial#172]
I use the LangSam to segment tif file,and can not installk groundingdino-py,then i install it by pip,and get the error message as folow:

Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Lining\AppData\Local\Temp\pip-install-godyuld_\groundingdino-py_3354b3ab580b4d9f8d19e2f3a8521336\setup.py", line 41, in <module>
          readme = readme_file.read()
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 2878: illegal multibyte sequence

**Comment by skylning** [comment]
move to groundingdino
