### ISSUE TITLE
ImportError: DLL load failed while importing etree: The specified procedure could not be found.

### ISSUE THREAD

**Issue by S-AQ** [opengeos/segment-geospatial#265]
### Environment Information

-   samgeo version: didn't manage to download
-   Python version: 3.11
-   Operating System: Windows 11
-   ArcGISPro version: 3.2.2

### Description

Followed [the tutorial for samgeo in ArcGISPro](https://samgeo.gishub.org/examples/arcgis/). 
At step 6 it was time to install the important Python modules, but then an error occurred in Mamba

### What I Did

My environment is called `seg_any_geo` and I ran the following:
```
mamba install arcpy deep-learning-essentials segment-geospatial pygis -c esri -c conda-forge
```
Then I received the following error: 
```
Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: / "By downloading and using the cuDNN conda packages, you accept the terms and conditions of the NVIDIA cuDNN EULA - https://docs.nvidia.com/deeplearning/cudnn/sla/index.html"

| C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\nb_conda_kernels\install.py:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/l
  from pkg_resources import iter_entry_points
Enabling nb_conda_kernels...
CONDA_PREFIX: C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo
Status: enabled

/ Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\__init__.py", line 3, in <module>
    from arcgis.auth.tools import LazyLoader
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\__init__.py", line 1, in <module>
    from .api import EsriSession
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\api.py", line 40, in <module>
    from ._auth import (
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\_auth\__init__.py", line 11, in <module>
    from ._token import (
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\_auth\_token.py", line 3, in <module>
    import lxml.html
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\lxml\html\__init__.py", line 49, in <module>
    from .. import etree
ImportError: DLL load failed while importing etree: The specified procedure could not be found.
Config option `kernel_spec_manager_class` not recognized by `InstallNBExtensionApp`.
Traceback (most recent call last):
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Scripts\jupyter-nbextension-script.py", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\jupyter_core\application.py", line 280, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 972, in start
    super().start()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\jupyter_core\application.py", line 258, in start
    self.subapp.start()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 702, in start
    self.install_extensions()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 675, in install_extensions
    full_dests = install(self.extra_args[0],
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 203, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
        ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\__init__.py", line 3, in <module>
    from arcgis.auth.tools import LazyLoader
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\__init__.py", line 1, in <module>
    from .api import EsriSession
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\api.py", line 40, in <module>
    from ._auth import (
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\_auth\__init__.py", line 11, in <module>
    from ._token import (
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\_auth\_token.py", line 3, in <module>
    import lxml.html
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\lxml\html\__init__.py", line 49, in <module>
    from .. import etree
ImportError: DLL load failed while importing etree: The specified procedure could not be found.
Config option `kernel_spec_manager_class` not recognized by `EnableNBExtensionApp`.
Traceback (most recent call last):
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Scripts\jupyter-nbextension-script.py", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\jupyter_core\application.py", line 280, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 972, in start
    super().start()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\jupyter_core\application.py", line 258, in start
    self.subapp.start()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 882, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 855, in toggle_nbextension_python
    return toggle(module,
           ^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 470, in enable_nbextension_python
    return _set_nbextension_state_python(True, module, user, sys_prefix,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 368, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
        ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\__init__.py", line 3, in <module>
    from arcgis.auth.tools import LazyLoader
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\__init__.py", line 1, in <module>
    from .api import EsriSession
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\api.py", line 40, in <module>
    from ._auth import (
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\_auth\__init__.py", line 11, in <module>
    from ._token import (
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\_auth\_token.py", line 3, in <module>
    import lxml.html
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\lxml\html\__init__.py", line 49, in <module>
    from .. import etree
ImportError: DLL load failed while importing etree: The specified procedure could not be found.

| Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcpy_init.py", line 234, in install
    from lxml import etree
ImportError: DLL load failed while importing etree: The specified procedure could not be found.

done
ERROR conda.core.link:_execute(949): An error occurred while installing package 'esri::arcgis-2.3.0-py311_6408'.
Rolling back transaction: done
post-link script failed for package esri::arcgis-2.3.0-py311_6408
location of failed script: C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Scripts\.arcgis-post-link.bat
==> script messages <==
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\__init__.py", line 3, in <module>
    from arcgis.auth.tools import LazyLoader
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\__init__.py", line 1, in <module>
    from .api import EsriSession
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\api.py", line 40, in <module>
    from ._auth import (
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\_auth\__init__.py", line 11, in <module>
    from ._token import (
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\_auth\_token.py", line 3, in <module>
    import lxml.html
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\lxml\html\__init__.py", line 49, in <module>
    from .. import etree
ImportError: DLL load failed while importing etree: The specified procedure could not be found.
Config option `kernel_spec_manager_class` not recognized by `InstallNBExtensionApp`.
Traceback (most recent call last):
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Scripts\jupyter-nbextension-script.py", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\jupyter_core\application.py", line 280, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 972, in start
    super().start()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\jupyter_core\application.py", line 258, in start
    self.subapp.start()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 702, in start
    self.install_extensions()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 675, in install_extensions
    full_dests = install(self.extra_args[0],
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 203, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
        ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\__init__.py", line 3, in <module>
    from arcgis.auth.tools import LazyLoader
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\__init__.py", line 1, in <module>
    from .api import EsriSession
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\api.py", line 40, in <module>
    from ._auth import (
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\_auth\__init__.py", line 11, in <module>
    from ._token import (
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\_auth\_token.py", line 3, in <module>
    import lxml.html
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\lxml\html\__init__.py", line 49, in <module>
    from .. import etree
ImportError: DLL load failed while importing etree: The specified procedure could not be found.
Config option `kernel_spec_manager_class` not recognized by `EnableNBExtensionApp`.
Traceback (most recent call last):
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Scripts\jupyter-nbextension-script.py", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\jupyter_core\application.py", line 280, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 972, in start
    super().start()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\jupyter_core\application.py", line 258, in start
    self.subapp.start()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 882, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 855, in toggle_nbextension_python
    return toggle(module,
           ^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 470, in enable_nbextension_python
    return _set_nbextension_state_python(True, module, user, sys_prefix,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 368, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
        ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\__init__.py", line 3, in <module>
    from arcgis.auth.tools import LazyLoader
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\__init__.py", line 1, in <module>
    from .api import EsriSession
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\api.py", line 40, in <module>
    from ._auth import (
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\_auth\__init__.py", line 11, in <module>
    from ._token import (
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\_auth\_token.py", line 3, in <module>
    import lxml.html
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\lxml\html\__init__.py", line 49, in <module>
    from .. import etree
ImportError: DLL load failed while importing etree: The specified procedure could not be found.

==> script output <==
stdout: jupyter nbextension command failed: map widgets in the jupyter notebook may not work, installation continuing...
jupyter nbextension command failed: map widgets in the jupyter notebook may not work, installation continuing...

stderr:
return code: 1

()


LinkError: post-link script failed for package esri::arcgis-2.3.0-py311_6408
location of failed script: C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Scripts\.arcgis-post-link.bat
==> script messages <==
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\__init__.py", line 3, in <module>
    from arcgis.auth.tools import LazyLoader
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\__init__.py", line 1, in <module>
    from .api import EsriSession
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\api.py", line 40, in <module>
    from ._auth import (
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\_auth\__init__.py", line 11, in <module>
    from ._token import (
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\_auth\_token.py", line 3, in <module>
    import lxml.html
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\lxml\html\__init__.py", line 49, in <module>
    from .. import etree
ImportError: DLL load failed while importing etree: The specified procedure could not be found.
Config option `kernel_spec_manager_class` not recognized by `InstallNBExtensionApp`.
Traceback (most recent call last):
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Scripts\jupyter-nbextension-script.py", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\jupyter_core\application.py", line 280, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 972, in start
    super().start()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\jupyter_core\application.py", line 258, in start
    self.subapp.start()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 702, in start
    self.install_extensions()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 675, in install_extensions
    full_dests = install(self.extra_args[0],
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 203, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
        ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\__init__.py", line 3, in <module>
    from arcgis.auth.tools import LazyLoader
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\__init__.py", line 1, in <module>
    from .api import EsriSession
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\api.py", line 40, in <module>
    from ._auth import (
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\_auth\__init__.py", line 11, in <module>
    from ._token import (
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\_auth\_token.py", line 3, in <module>
    import lxml.html
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\lxml\html\__init__.py", line 49, in <module>
    from .. import etree
ImportError: DLL load failed while importing etree: The specified procedure could not be found.
Config option `kernel_spec_manager_class` not recognized by `EnableNBExtensionApp`.
Traceback (most recent call last):
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Scripts\jupyter-nbextension-script.py", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\jupyter_core\application.py", line 280, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 972, in start
    super().start()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\jupyter_core\application.py", line 258, in start
    self.subapp.start()
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 882, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 855, in toggle_nbextension_python
    return toggle(module,
           ^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 470, in enable_nbextension_python
    return _set_nbextension_state_python(True, module, user, sys_prefix,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 368, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
        ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\__init__.py", line 3, in <module>
    from arcgis.auth.tools import LazyLoader
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\__init__.py", line 1, in <module>
    from .api import EsriSession
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\api.py", line 40, in <module>
    from ._auth import (
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\_auth\__init__.py", line 11, in <module>
    from ._token import (
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\arcgis\auth\_auth\_token.py", line 3, in <module>
    import lxml.html
  File "C:\Users\someone\AppData\Local\ESRI\conda\envs\seg_any_geo\Lib\site-packages\lxml\html\__init__.py", line 49, in <module>
    from .. import etree
ImportError: DLL load failed while importing etree: The specified procedure could not be found.

==> script output <==
stdout: jupyter nbextension command failed: map widgets in the jupyter notebook may not work, installation continuing...
jupyter nbextension command failed: map widgets in the jupyter notebook may not work, installation continuing...

stderr:
return code: 1

()
```

**Comment by giswqs** [comment]
I just tested it with ArcGIS Pro 3.3, and everything works fine. Please upldate to ArcGIS 3.3 and try again.

![Screenshot_20240517_220453](https://github.com/opengeos/segment-geospatial/assets/5016453/d636181a-0367-46dc-ad16-f726e416b22e)
