### ISSUE TITLE
TypeError: TileClient.__init__() got an unexpected keyword argument 'cors_all'

### ISSUE THREAD

**Issue by brianmcdonald** [opengeos/segment-geospatial#309]
### Environment Information

-   samgeo version: '0.10.7'
-   Python version: Python 3.12.4
-   Operating System: macOS 14.6.1 with Safari 17.6

### Description

I am trying to run the examples, but getting an error when creating the interactive maps. For instance, while running input_prompts.ipynb, the cell

```
m.layers[-1].visible = False
m.add_raster(image, layer_name="Image")
m
```

gives the error:

```
Exception ignored in: <function TileClient.__del__ at 0x33ad61120>
Traceback (most recent call last):
  File "[/Users/brian/miniforge3/envs/eth/lib/python3.12/site-packages/localtileserver/server.py", line 152](http://localhost:8888/Users/brian/miniforge3/envs/eth/lib/python3.12/site-packages/localtileserver/server.py#line=151), in __del__
    self.shutdown()
  File "[/Users/brian/miniforge3/envs/eth/lib/python3.12/site-packages/localtileserver/server.py", line 174](http://localhost:8888/Users/brian/miniforge3/envs/eth/lib/python3.12/site-packages/localtileserver/server.py#line=173), in shutdown
    shutdown_server(self._key, force=force)
                    ^^^^^^^^^
AttributeError: 'TileClient' object has no attribute '_key'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[/var/folders/q2/r6cyvbjx443d2txp6kr8tl_h0000gn/T/ipykernel_61098/3537108183.py](http://localhost:8888/var/folders/q2/r6cyvbjx443d2txp6kr8tl_h0000gn/T/ipykernel_61098/3537108183.py) in ?()
      1 m.layers[-1].visible = False
----> 2 m.add_raster(image, layer_name="Image")
      3 m

[~/miniforge3/envs/eth/lib/python3.12/site-packages/leafmap/leafmap.py](http://localhost:8888/~/miniforge3/envs/eth/lib/python3.12/site-packages/leafmap/leafmap.py) in ?(self, source, indexes, colormap, vmin, vmax, nodata, attribution, layer_name, layer_index, zoom_to_layer, visible, opacity, array_args, client_args, **kwargs)
   2351 
   2352         if isinstance(source, np.ndarray) or isinstance(source, xr.DataArray):
   2353             source = array_to_image(source, **array_args)
   2354 
-> 2355         tile_layer, tile_client = get_local_tile_layer(
   2356             source,
   2357             indexes=indexes,
   2358             colormap=colormap,

[~/miniforge3/envs/eth/lib/python3.12/site-packages/leafmap/common.py](http://localhost:8888/~/miniforge3/envs/eth/lib/python3.12/site-packages/leafmap/common.py) in ?(source, port, debug, indexes, colormap, vmin, vmax, nodata, attribution, tile_format, layer_name, client_args, return_client, quiet, **kwargs)
   2958         else:
   2959             layer_name = "LocalTile_" + random_string(3)
   2960 
   2961     if isinstance(source, str) or isinstance(source, rasterio.io.DatasetReader):
-> 2962         tile_client = TileClient(source, port=port, debug=debug, **client_args)
   2963     else:
   2964         tile_client = source
   2965 

TypeError: TileClient.__init__() got an unexpected keyword argument 'cors_all'
```

### What I Did

created the an env and installed the required packages

**Comment by giswqs** [comment]
Can you try update the packages?
```bash
pip install -U leafmap localtileserver
```

**Comment by Joaquin-Urruti** [comment]
Hi!!

Having created a conda env, I'm having the same problem as mentioned by [brianmcdonald]
I tryied installing different versions of localtileserver and also tryied:
- pip install -U leafmap localtileserver, and 
- from osgeo import gdal
but was not able to make it work.

My sistem details are the following:
macOS 14.6.1 (23G93)
Apple M2 Pro
32Gb RAM

Some conda env details:
  - python=3.12.6
  - gdal=3.9.2
  - segment-anything=1.0.1
  - segment-anything-fast=0.1.2=
  - segment-anything-hq=0.3
  - segment-geospatial=0.11.0
  - localtileserver=0.10.3
  - large-image==1.29.9
  - large-image-source-gdal==1.29.9
  - leafmap==0.37.3

This is the error I'm getting:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File ~/anaconda3/envs/sam2/lib/python3.12/site-packages/flask_restx/api.py:18
     [17](https://file+.vscode-resource.vscode-cdn.net/Users/ju/Library/CloudStorage/GoogleDrive-urrutijoaquin%40gmail.com/Mi%20unidad/Python%20Scripts/Sustentabilidad/~/anaconda3/envs/sam2/lib/python3.12/site-packages/flask_restx/api.py:17) try:
---> [18](https://file+.vscode-resource.vscode-cdn.net/Users/ju/Library/CloudStorage/GoogleDrive-urrutijoaquin%40gmail.com/Mi%20unidad/Python%20Scripts/Sustentabilidad/~/anaconda3/envs/sam2/lib/python3.12/site-packages/flask_restx/api.py:18)     from flask.helpers import _endpoint_from_view_func
     [19](https://file+.vscode-resource.vscode-cdn.net/Users/ju/Library/CloudStorage/GoogleDrive-urrutijoaquin%40gmail.com/Mi%20unidad/Python%20Scripts/Sustentabilidad/~/anaconda3/envs/sam2/lib/python3.12/site-packages/flask_restx/api.py:19) except ImportError:

ImportError: cannot import name '_endpoint_from_view_func' from 'flask.helpers' (/Users/ju/anaconda3/envs/sam2/lib/python3.12/site-packages/flask/helpers.py)

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
File ~/anaconda3/envs/sam2/lib/python3.12/site-packages/leafmap/common.py:166, in check_package(name, URL)
    [165](https://file+.vscode-resource.vscode-cdn.net/Users/ju/Library/CloudStorage/GoogleDrive-urrutijoaquin%40gmail.com/Mi%20unidad/Python%20Scripts/Sustentabilidad/~/anaconda3/envs/sam2/lib/python3.12/site-packages/leafmap/common.py:165) try:
--> [166](https://file+.vscode-resource.vscode-cdn.net/Users/ju/Library/CloudStorage/GoogleDrive-urrutijoaquin%40gmail.com/Mi%20unidad/Python%20Scripts/Sustentabilidad/~/anaconda3/envs/sam2/lib/python3.12/site-packages/leafmap/common.py:166)     __import__(name.lower())
    [167](https://file+.vscode-resource.vscode-cdn.net/Users/ju/Library/CloudStorage/GoogleDrive-urrutijoaquin%40gmail.com/Mi%20unidad/Python%20Scripts/Sustentabilidad/~/anaconda3/envs/sam2/lib/python3.12/site-packages/leafmap/common.py:167) except Exception:

File ~/anaconda3/envs/sam2/lib/python3.12/site-packages/localtileserver/__init__.py:3
      [2](https://file+.vscode-resource.vscode-cdn.net/Users/ju/Library/CloudStorage/GoogleDrive-urrutijoaquin%40gmail.com/Mi%20unidad/Python%20Scripts/Sustentabilidad/~/anaconda3/envs/sam2/lib/python3.12/site-packages/localtileserver/__init__.py:2) from localtileserver._version import __version__
----> [3](https://file+.vscode-resource.vscode-cdn.net/Users/ju/Library/CloudStorage/GoogleDrive-urrutijoaquin%40gmail.com/Mi%20unidad/Python%20Scripts/Sustentabilidad/~/anaconda3/envs/sam2/lib/python3.12/site-packages/localtileserver/__init__.py:3) from localtileserver.client import TileClient, get_or_create_tile_client
      [4](https://file+.vscode-resource.vscode-cdn.net/Users/ju/Library/CloudStorage/GoogleDrive-urrutijoaquin%40gmail.com/Mi%20unidad/Python%20Scripts/Sustentabilidad/~/anaconda3/envs/sam2/lib/python3.12/site-packages/localtileserver/__init__.py:4) from localtileserver.helpers import hillshade, parse_shapely, polygon_to_geojson, save_new_raster

File ~/anaconda3/envs/sam2/lib/python3.12/site-packages/localtileserver/client.py:22
     [21](https://file+.vscode-resource.vscode-cdn.net/Users/ju/Library/CloudStorage/GoogleDrive-urrutijoaquin%40gmail.com/Mi%20unidad/Python%20Scripts/Sustentabilidad/~/anaconda3/envs/sam2/lib/python3.12/site-packages/localtileserver/client.py:21) from localtileserver.configure import get_default_client_params
---> [22](https://file+.vscode-resource.vscode-cdn.net/Users/ju/Library/CloudStorage/GoogleDrive-urrutijoaquin%40gmail.com/Mi%20unidad/Python%20Scripts/Sustentabilidad/~/anaconda3/envs/sam2/lib/python3.12/site-packages/localtileserver/client.py:22) from localtileserver.manager import AppManager
...
--> 168         raise ImportError(
    169             f"{name} is not installed. Please install it before proceeding. {URL}"
    170         )

ImportError: localtileserver is not installed. Please install it before proceeding. https://github.com/banesullivan/localtileserver

**Comment by brianmcdonald** [comment]
Hi @Joaquin-Urruti 
The solution that worked for me in the end was to use the UV package manager to install segment-geospatial and GDAL.
https://github.com/astral-sh/uv

**Comment by giswqs** [comment]
The recommended way is to use conda to install samgeo. Installing GDAL using pip can be challengine. 

```bash
conda create -n geo python
conda activate geo
conda install -c conda-forge mamba
mamba install -c conda-forge segment-geospatial
```

**Comment by giswqs** [comment]
You can also checkout the MacOS GitHub Actions on how to install samgeo on MacOS. 
https://github.com/opengeos/segment-geospatial/blob/main/.github/workflows/macos.yml

**Comment by Joaquin-Urruti** [comment]
> Hi @Joaquin-Urruti The solution that worked for me in the end was to use the UV package manager to install segment-geospatial and GDAL. https://github.com/astral-sh/uv

Intresting Brian, I've just tested a little uv this days. Thanks!

**Comment by Joaquin-Urruti** [comment]
Thanks a lot for the info @giswqs! I'll try that. Best regards!

**Comment by Joaquin-Urruti** [comment]
Thank you both @giswqs and @brianmcdonald,

I creted a new env like this and works fine:
conda create -n geo python
conda activate geo
conda install -c conda-forge mamba
mamba install -c conda-forge segment-geospatial
