### ISSUE TITLE
 HELP: jupyter log output : assert 0 < size <= self._size  when i use leafmap 

### ISSUE THREAD

**Issue by Bean95zx** [opengeos/segment-geospatial#60]
![image](https://github.com/opengeos/segment-geospatial/assets/44997999/43a6122e-fc17-4194-b386-4bfbfd672cf4)
when i use leafmap to draw a rectangle， the jupyter usually output a error.
`Traceback (most recent call last):
  File "/sdisk/shome/speed/anaconda3/envs/samgeoNew/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/sdisk/shome/speed/anaconda3/envs/samgeoNew/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "/sdisk/shome/speed/anaconda3/envs/samgeoNew/lib/python3.9/site-packages/tornado/iostream.py", line 702, in _handle_events
    self._handle_write()
  File "/sdisk/shome/speed/anaconda3/envs/samgeoNew/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
    self._write_buffer.advance(num_bytes)
  File "/sdisk/shome/speed/anaconda3/envs/samgeoNew/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
    assert 0 < size <= self._size
AssertionError`

**Comment by giswqs** [comment]
This seems an ipyleaflet/ipywidgets installation issue rather than not a segment-geospatial issue. Try creating a fresh conda env to install the packages.

```bash
conda install -n base mamba -c conda-forge
mamba create -n geo segment-geospatial leafmap localtileserver -c conda-forge
```
